insert into DESTINATION(NAME, DESCRIPTION, AUDIO, COORDX, COORDY)
values ('Galerie Werenne', 'Jadis prestigieuse avec ses commerces chics et son style art déco, la galerie Wérenne est aujourd''hui en piteux état.', 'http://noAudioYet.com', 50.468061, 4.863362);
insert into DESTINATION(NAME, DESCRIPTION, AUDIO, COORDX, COORDY)
values ('Grand Casino de Namur', 'Le casino de Namur (anciennement appelé Kursaal) est un établissement de jeux et loisirs avec hôtel de standing sis au pied de la citadelle et en bord de Meuse, à la sortie de Namur vers La Plante, en Belgique. Un bâtiment double de style Art déco est édifié au début du XXe siècle et inauguré en 1914. Détruit par un incendie en 1980, le bâtiment méridional est reconstruit et inauguré en 1986. ', 'http://noAudioYet.com', 50.457232, 4.863294);
insert into DESTINATION(NAME, DESCRIPTION, AUDIO, COORDX, COORDY)
values ('Citadelle de Namur', 'La citadelle de Namur, en Belgique, est une ancienne place forte dominant la ville et le confluent. Il s''agit d''une des plus grandes citadelles d''Europe et son vaste réseau de souterrains lui valut d''être surnommée "La termitière de l''Europe" par Napoléon Ier. Des vestiges du château comtal aux bastions et terrasses à canons plus récents, elle témoigne de plus de mille ans d''histoire. ', 'http://noAudioYet.com', 50.459964, 4.861235);
insert into DESTINATION(NAME, DESCRIPTION, AUDIO, COORDX, COORDY)
values ('Parc attractif Reine Fabiola', 'Le parc attractif Reine Fabiola est un parc de loisirs belge fondé en 1959 qui est aujourd''hui géré par le service Jeunesse de la Ville de Namur. ', 'http://noAudioYet.com', 50.458434, 4.852565);
insert into DESTINATION(NAME, DESCRIPTION, AUDIO, COORDX, COORDY)
values ('Musée Provincial des Arts Anciens du Namurois - Trésor d''Oignies (Trem.a)', 'Le TreM.a – Musée des Arts anciens du Namurois, créé en 1964, en partenariat avec la Société archéologique de Namur, est hébergé dans l’Hôtel de Gaiffier d’Hestroy, reçu en legs à cette fin, en 1950, par la Province de Namur. Il présente des collections d’histoire et d’histoire de l''art dont la reconnaissance est internationale, notamment le Trésor d’Oignies (13e siècle) et la collection des peintures de Henri Bles (milieu du 16e siècle).', 'http://noAudioYet.com', 50.465708, 4.865373);
insert into DESTINATION(NAME, DESCRIPTION, AUDIO, COORDX, COORDY)
values ('Théâtre de Namur', 'Le Théâtre de Namur est, depuis 1998, au cœur de la capitale de la Région wallonne un espace de création et de diffusion en arts de la scène. Son siège et sa salle principale sont situés au Théâtre royal de Namur, un théâtre à l''italienne du XIXe siècle. ', 'http://noAudioYet.com', 50.464547, 4.868046);
insert into DESTINATION(NAME, DESCRIPTION, AUDIO, COORDX, COORDY)
values ('Musée provincial Félicien Rops', 'Situé dans un ancien hôtel de maître du vieux Namur, dans une zone piétonne, le musée présente la vie et l’œuvre de Félicien Rops de ses débuts comme caricaturiste à ses travaux sataniques et sulfureux.', 'http://noAudioYet.com', 50.463207, 4.862537);
insert into DESTINATION(NAME, DESCRIPTION, AUDIO, COORDX, COORDY)
values ('Namur Expo', 'Un centre d''expo', 'http://noAudioYet.com', 50.466972, 4.848238);
insert into DESTINATION(NAME, DESCRIPTION, AUDIO, COORDX, COORDY)
values ('Chapelle Saint Albert', 'Une chapelle', 'http://noAudioYet.com', 50.453149, 4.843134);
insert into DESTINATION(NAME, DESCRIPTION, AUDIO, COORDX, COORDY)
values ('Gare de Namur', 'La gare de Namur est une gare ferroviaire belge située à Namur, au nord de la Corbeille, le centre historique de la ville. Le sillon ferroviaire est établi sur un ancien bras de Sambre qui ceinturait anciennement le rempart nord de la ville. Elle est un élément essentiel du réseau wallon du fait de sa situation géographique : les lignes raccordant les parties est-ouest et nord-sud du territoire wallon passant toutes par Namur. Elle est d''ailleurs la première gare wallonne par le nombre de voyageurs, avec 18.649 passagers entrants par jour ouvrable en 2012, devant la gare d''Ottignies (17.240) et la gare de Liège-Guillemins (16.807)', 'http://noAudioYet.com', 50.468518, 4.862092);
insert into DESTINATION(NAME, DESCRIPTION, AUDIO, COORDX, COORDY)
values ('Beffroi de Namur', 'Le Beffroi de Namur, également appelé Tour Saint-Jacques, est un bâtiment historique de la ville de Namur en Belgique. La tour, construite vers 1388 comme partie de l’enceinte de la ville devint beffroi en 1746. Il est un des 56 Beffrois de Belgique et de France classés au patrimoine mondial de l’UNESCO. ', 'http://noAudioYet.com', 50.463863, 4.867137);
insert into DESTINATION(NAME, DESCRIPTION, AUDIO, COORDX, COORDY)
values ('Parlement de Wallonie', 'L’hospice Saint-Gilles est une institution hospitalière d''origine médiévale et reconstruite à la Renaissance, sise en bord de Meuse, au départ de la rue Notre-Dame, à Namur (Belgique). Construit et ouvert comme hôpital au XIIIe siècle, il devint et resta hospice jusqu’en 1965. Entièrement rénové, il est depuis 1998 le siège du Parlement de Wallonie. ', 'http://noAudioYet.com', 50.460958, 4.867863);
insert into DESTINATION(NAME, DESCRIPTION, AUDIO, COORDX, COORDY)
values ('Eglise Saint-Loup', 'Jouxtant le collège,  les pères construisent entre 1621 et 1645, une chapelle dédiée à Saint-Ignace - d’après les plans du père Jésuite Huyssens,  architecte de l''église Saint-Michel de Louvain.  En 1773, sous le règne de l''impératrice Marie-Thérèse, la Compagnie est interdite dans nos régions. La chapelle devient l’église paroissiale Saint-Loup. Entre 1860 et 1867, la façade de pierre en calcaire de Meuse et pierre blanche est remontée.', 'http://noAudioYet.com', 50.463965, 4.863254);
insert into DESTINATION(NAME, DESCRIPTION, AUDIO, COORDX, COORDY)
values ('Théâtre de verdure', 'Le Théâtre de Verdure de Namur est un théâtre de verdure situé à Namur (Belgique). Le Théâtre de Verdure a été érigé par l’architecte Georges Hobé en 1908. À l’origine, il accueillait des opéras, des concerts de la danse, des spectacles de variétés. Le festival Verdur Rock s''y déroule depuis 1985. Il devrait, à l’avenir, retrouver sa vocation à la fois touristique et culturelle. Lieu de distraction, il est aussi un espace d’échanges et de réunions où se croisent comédiens, chanteurs, musiciens, visiteurs… ', 'http://noAudioYet.com', 50.456187, 4.856529);
insert into DESTINATION(NAME, DESCRIPTION, AUDIO, COORDX, COORDY)
values ('UNamur Faculté d''Informatique', 'La faculté d''informatique, anciennement l''Institut d''informatique, est décrite comme le « pionnier de l''enseignement de l''informatique en Belgique. » en raison de son inauguration très précoce (dès 1973).', 'http://noAudioYet.com', 50.465959, 4.857663);